apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-objects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stantaov/k8s-max.git
    targetRevision: HEAD
    path: deployments/ingress-objects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true