annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Update application version of n8n 1.33.1"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.33.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.6.1
description: A Kubernetes Helm chart for n8n a free and open fair-code licensed node
  based Workflow Automation Tool. Easily automate tasks across different services.
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
- Workflow Automation
- Workflow
- iPaaS
- integration-framework
- low-code-plattform
- low-code
maintainers:
- email: contact@8gears.com
  name: 8gears AG
- email: _@8gears.com
  name: n8n Community
name: n8n
sources:
- https://github.com/n8n-io/n8n
- https://n8n.io/
type: application
version: 0.23.0
