# Default helm values for n8n.

n8n:
  encryption_key: ""

config:
  database:
    type: postgresdb
    postgresdb:
      database: n8n
      host: postgres.affine.svc.cluster.local 
      port: 5432
      user: affine 
      schema: public
  executions:
    pruneData: "true"
    pruneDataMaxAge: 8760
  generic:
    timezone: "UTC" 
  scaling:
    enabled: true
    redis:
      host: redis.affine.svc.cluster.local 
      port: 6379

secret:
  database:
    postgresdb:
      password: "" 

extraEnvSecrets:
  DB_POSTGRESDB_PASSWORD:
    name: affine-secrets
    key: DB_PASSWORD 
  # REDIS_PASSWORD:
  #   name: affine-secrets
  #   key: redis-password

persistence:
  enabled: true
  type: dynamic
  storageClass: "longhorn" 
  accessModes:
    - ReadWriteOnce
  size: 5Gi

replicaCount: 1

deploymentStrategy:
  type: "RollingUpdate"
  maxSurge: "25%"
  maxUnavailable: "25%"

image:
  repository: n8nio/n8n
  pullPolicy: Always 
  tag: "1.91.3" 

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: n8n.k8s.max
      paths:
        - path: /
          pathType: Prefix
  tls: []
  className: ""

workerResources: {}
webhookResources: {}
resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 200m
  #   memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

scaling:
  enabled: true
  worker:
    count: 2
    concurrency: 10
  webhook:
    enabled: false
    count: 1

redis:
  enabled: false 
