replicaCount: 1

image:
  repository: stantaov/excalidraw
  pullPolicy: IfNotPresent
  tag: "1.0.1"

imagePullSecrets: []
nameOverride: excalidraw
fullnameOverride: excalidraw

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  type: LoadBalancer
  port: 80
  headless: false

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: excalidraw.k8s.max
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - excalidraw.k8s.max
      secretName: k8s-max-wildcard-tls

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
