---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: affine-secrets
  namespace: affine
spec:
  encryptedData:
    DB_PASSWORD: AgB7LlaoA0cA9pnkxFYphk/AQMPV/q0rKFtxwFoPa/b2foM+04E4ve5H3kDQ+GFHi8XTlEJl8UhbUxluTm7ykVZTYKvQaXin3KIypNQOXEdl7jxScjJOzWrP2GKLY0o8eugC9zD2a9xCG852I78//ErUXYJ7TZ4UOlp0UGCQjvB+8vOMgVy8+B6uoUhovRLZMTKNMZq2aGIjxCKYrBNICu+LMkBbsqhTdIOjYX+dSya50tpvTt4734qzOe11iiHFvg3pMchthXD8q1yxDpsTPdJCHJ/icIkoxFohXi/zd9QfPlZ78t/Hc4FmYufzoieNUi1bXDenI+yX9sf8DVtXuMZbA1nHxDAAVRbaLJcRwiFqkb5mgRvIGDg5OMkVwTRn8WmqUrguBfCMeDGzC6GkvltVLRiIa0DAciZYPZlSfXAo0VaRF65wOh980FXEC3e3DCjg3YTR5qWSVQ/zCUfVDtYQy1GhmxUV2KEnGPMyT7f74+RMixnjBjj3OPOJGUGPnbz4dpVDKvVgo5RfIWUK6hrVAC2oip7ZvrZjR8yOSNqDTUWYhJYB+VkZNjylcgN51pOWcwCZyP8pO2j5VZN8Iv/Nho333V0mATJQt/x/WO566+KwXvW1VlSuu2X3YVUbfPSgSq8D7moN2FvemwMTeDmrHCdOvmJ7pmm787+SOBG9TaE/0er1UU116LmZ99Tya5KmpFwdxIW/ukU=
  template:
    metadata:
      creationTimestamp: null
      name: affine-secrets
      namespace: affine
    type: Opaque
